# mpz is a distinct C type, not an int subclass; the stub narrows it to int because every
# use here is integral arithmetic, comparison or int() and no int-only API is reached.
class mpz(int): ...

def invert(x: int, m: int) -> mpz: ...
def isqrt(x: int) -> mpz: ...
